name: Validate Secrets

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check required GitHub Secrets presence
        run: |
          set -euo pipefail
          missing=()

          is_empty() { [ -z "$1" ]; }

          is_empty "${{ secrets.SSH_PRIVATE_KEY }}" && missing+=("SSH_PRIVATE_KEY")
          is_empty "${{ secrets.SSH_HOST }}" && missing+=("SSH_HOST")
          is_empty "${{ secrets.SSH_PORT }}" && missing+=("SSH_PORT")
          is_empty "${{ secrets.SSH_USER }}" && missing+=("SSH_USER")
          is_empty "${{ secrets.SSH_TARGET_DIR }}" && missing+=("SSH_TARGET_DIR")

          is_empty "${{ secrets.TRADING_MODE }}" && missing+=("TRADING_MODE")
          is_empty "${{ secrets.BINANCE_API_KEY }}" && missing+=("BINANCE_API_KEY")
          is_empty "${{ secrets.BINANCE_SECRET_KEY }}" && missing+=("BINANCE_SECRET_KEY")
          is_empty "${{ secrets.BINANCE_TEST_API_KEY }}" && missing+=("BINANCE_TEST_API_KEY")
          is_empty "${{ secrets.BINANCE_TEST_SECRET_KEY }}" && missing+=("BINANCE_TEST_SECRET_KEY")

          is_empty "${{ secrets.OPENAI_API_KEY }}" && missing+=("OPENAI_API_KEY")
          is_empty "${{ secrets.APIFY_API_TOKEN }}" && missing+=("APIFY_API_TOKEN")
          is_empty "${{ secrets.TWITTER_BEARER_TOKEN }}" && missing+=("TWITTER_BEARER_TOKEN")
          is_empty "${{ secrets.TELEGRAM_BOT_TOKEN }}" && missing+=("TELEGRAM_BOT_TOKEN")
          is_empty "${{ secrets.TELEGRAM_CHAT_ID }}" && missing+=("TELEGRAM_CHAT_ID")

          if [ ${#missing[@]} -gt 0 ]; then
            echo "Missing GitHub Secrets: ${missing[*]}" >&2
            exit 2
          fi
          echo "All required secrets are set (values not printed)."